umg:
  host: "192.168.1.30"
  http_port: 80
  modbus_port: 502
  timeout_s: 3
  unit_id: 1
  registers:
    power_active_l1: 19020
    power_active_l2: 19022
    power_active_l3: 19024
    power_active_total: 19026
    power_reactive_l1: 19036
    power_reactive_l2: 19038
    power_reactive_l3: 19040
    power_reactive_total: 19042
    power_apparent_l1: 19028
    power_apparent_l2: 19030
    power_apparent_l3: 19032
    power_apparent_total: 19034
    energy_active_import_l1: 13987
    energy_active_import_l2: 13989
    energy_active_import_l3: 13991
    energy_active_import_total: 13997
    energy_active_export_l1: 13999
    energy_active_export_l2: 14001
    energy_active_export_l3: 14003
    energy_active_export_total: 14009
    energy_export_global_l1: 19070
    energy_export_global_l2: 19072
    energy_export_global_l3: 19074
    energy_export_global_total: 19076
    energy_reactive_total_l1: 13975
    energy_reactive_total_l2: 13977
    energy_reactive_total_l3: 13979
    energy_reactive_total_sum: 13985
    energy_reactive_inductive_l1: 14059
    energy_reactive_inductive_l2: 14061
    energy_reactive_inductive_l3: 14063
    energy_reactive_inductive_sum: 14069
    energy_reactive_capacitive_l1: 14071
    energy_reactive_capacitive_l2: 14073
    energy_reactive_capacitive_l3: 14075
    energy_reactive_capacitive_sum: 14081
    cos_phi_l1: 19044
    cos_phi_l2: 19046
    cos_phi_l3: 19048
    frequency: 19050
    voltage_l1_n: 19000
    voltage_l2_n: 19002
    voltage_l3_n: 19004
    voltage_l1_l2: 19006
    voltage_l2_l3: 19008
    voltage_l3_l1: 19010
    current_l1: 19012
    current_l2: 19014
    current_l3: 19016
    current_sum: 19018
    energy_active_import: 19062
    energy_active_export: 19070
    energy_reactive_import: 19094
    energy_reactive_export: 19102
    voltage_l1: 19000
    voltage_l2: 19002
    voltage_l3: 19004
    current_l1_avg: 19012
    current_l2_avg: 19014
    current_l3_avg: 19016
    power_factor: 19636
    thd_voltage_l1: 19110
    thd_current_l1: 19116

polling:
  interval_minutes: 1
  cycles_default: 1
  export_dir: "data/exports"
  modbus_retries: 3
  modbus_retry_delay_s: 1.0
  time_markers:
    - 5
    - 10
    - 15
    - 30
    - 60

vpn:
  auto_start: true
  auto_stop: true
  max_retries: 3
