pre:
  cod_pre: "ROPRE001"
  cod_brp: "ROBRP001"
  operator_name: "Parc Fotovoltaic Example"
  timezone: "Europe/Bucharest"
modbus:
  ip: "192.168.1.30"
  port: 80
  unit_id: 1
  timeout_s: 5.0
  retry_attempts: 3
  protocol: "http"
router:
  host: "10.0.0.1"
  snmp_enabled: true
  snmp_port: 161
  verify_tls: true
  ca_bundle: "config/certs/teltonika_ca.pem"
  openvpn_profile: "config/Prognoza-umg509_stable.ovpn"
  openvpn_executable: "C:/Program Files/OpenVPN/bin/openvpn.exe"
quality:
  max_thd_voltage: 8.0
  max_thd_current: 5.0
  min_power_factor: 0.9
  voltage_min_percent: -10.0
  voltage_max_percent: 10.0
deadlines:
  d_minus_1_notification: "15:00:00"
  reminder_offset_minutes: 30
  monthly_anre_day: 10
  monthly_anre_hour: 10
storage:
  database_url: "sqlite:///./prognoza.db"
  backup_dir: "backups"
  export_dir: "exports"
  keep_days: 365
weather:
  provider: "openweather"
  api_key: "set_api_key_here"
  latitude: 44.4268
  longitude: 26.1025
  forecast_horizon_hours: 48
  timezone: "Europe/Bucharest"
recipients:
  legal_representatives:
    - "legal@example.com"
  dispatch_contacts:
    - "dispatch@example.com"
  it_on_call:
    - "it@example.com"
extra:
  brp_endpoint: "https://brp.example.com/api"
umg_http:
  base_url: "http://192.168.1.30"
  timeout_s: 5.0
  verify_tls: false
  endpoints:
    power_active_total:
      path: "/api/measurements/19026"
      value_key: "value"
    power_reactive_total:
      path: "/api/measurements/19042"
      value_key: "value"
    power_apparent_total:
      path: "/api/measurements/19034"
      value_key: "value"
    energy_active_import:
      path: "/api/measurements/19062"
      value_key: "value"
    energy_active_export:
      path: "/api/measurements/19070"
      value_key: "value"
    energy_reactive_import:
      path: "/api/measurements/19094"
      value_key: "value"
    energy_reactive_export:
      path: "/api/measurements/19102"
      value_key: "value"
    voltage_l1:
      path: "/api/measurements/19000"
      value_key: "value"
    voltage_l2:
      path: "/api/measurements/19002"
      value_key: "value"
    voltage_l3:
      path: "/api/measurements/19004"
      value_key: "value"
    current_l1:
      path: "/api/measurements/19012"
      value_key: "value"
    current_l2:
      path: "/api/measurements/19014"
      value_key: "value"
    current_l3:
      path: "/api/measurements/19016"
      value_key: "value"
    frequency:
      path: "/api/measurements/19050"
      value_key: "value"
    power_factor:
      path: "/api/measurements/19636"
      value_key: "value"
    thd_voltage_l1:
      path: "/api/measurements/19110"
      value_key: "value"
    thd_current_l1:
      path: "/api/measurements/19116"
      value_key: "value"
