timezone: "Europe/Brezoaia"
location:
  lat: 44.538476
  lon: 25.795695
providers:
  - type: openweather
    priority: 10
    ttl: 1800           # seconds
    api_key: "${OPENWEATHER_API_KEY}"
  - type: openmeteo_ecmwf
    priority: 20
    ttl: 3600
    models: ["ecmwf", "icon"]
  - type: tomorrow_io
    priority: 30
    ttl: 900
    api_key: "${TOMORROW_IO_API_KEY}"
