# Weather Router Configuration
# This file configures weather data providers for the PROGNOZA system
# Site: Brezoaia Photovoltaic Park, Dambovita County, Romania

timezone: "Europe/Brezoaia"  # Brezoaia uses Europe/Bucharest timezone (aliased)

location:
  lat: 44.538476   # Latitude for Brezoaia PV Park, Dambovita, Romania
  lon: 25.795695   # Longitude for Brezoaia PV Park, Dambovita, Romania

# Provider configuration (ordered by priority)
# Lower priority number = higher preference
# The router will try providers in order and fill gaps with fallbacks

providers:
  # ========================================================================
  # FREE PROVIDERS (NO API KEY REQUIRED)
  # ========================================================================

  # Open-Meteo ECMWF - FREE, HIGH QUALITY, NO API KEY
  # Best choice for free weather data with ECMWF and ICON models
  - type: openmeteo_ecmwf
    priority: 10              # Highest priority - use this first
    ttl: 3600                 # Cache for 1 hour (model updates every 6h)
    models: ["ecmwf", "icon"] # ECMWF IFS + DWD ICON models
    # Available models: ecmwf_ifs04, icon_seamless, gfs_seamless, best_match

  # ========================================================================
  # PAID PROVIDERS (API KEY REQUIRED) - OPTIONAL
  # ========================================================================

  # OpenWeather One Call API - PAID (requires subscription)
  # One Call 3.0 requires "One Call by Call" plan (~$40/month for 1M calls)
  # Uncomment if you have a valid subscription
  # - type: openweather
  #   priority: 20
  #   ttl: 1800
  #   api_key: "${OPENWEATHER_API_KEY}"
  #   skip_on_auth_failure: true  # Skip silently if auth fails

  # Tomorrow.io - FREE TIER AVAILABLE (500 calls/day)
  # Uncomment and add API key if you want to use it
  # Sign up at: https://www.tomorrow.io/weather-api/
  # - type: tomorrow_io
  #   priority: 30
  #   ttl: 900
  #   api_key: "${TOMORROW_IO_API_KEY}"

# ========================================================================
# NOTES:
# ========================================================================
# 1. Open-Meteo is COMPLETELY FREE and provides excellent data quality
#    from ECMWF IFS and DWD ICON numerical weather models
#
# 2. For most use cases, Open-Meteo alone is sufficient
#
# 3. If you need additional providers, sign up for:
#    - Tomorrow.io free tier: 500 calls/day (good for nowcasting)
#    - OpenWeather paid: Only if you need their specific data
#
# 4. Environment variables can be set in .env file:
#    OPENWEATHER_API_KEY=your_key_here
#    TOMORROW_IO_API_KEY=your_key_here
#
# 5. Override timezone at runtime with:
#    $env:WEATHER_ROUTER_TZ="UTC"
